export default {
    apps: [
        {
            name: 'add-product-consumer',
            script: 'src/AddProductConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            // Disable monitoring to avoid wmic errors on Windows
            disable_logs: false,
            error_file: 'logs/add-product-consumer-error.log',
            out_file: 'logs/add-product-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'after-order-place-consumer',
            script: 'src/AfterOrderPlaceConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/after-order-place-consumer-error.log',
            out_file: 'logs/after-order-place-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'create-admin-consumer',
            script: 'src/CreateAdminConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/create-admin-consumer-error.log',
            out_file: 'logs/create-admin-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'create-user-consumer',
            script: 'src/CreateUserConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/create-user-consumer-error.log',
            out_file: 'logs/create-user-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'product-embedding-consumer',
            script: 'src/ProductEmbeddingConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/product-embedding-consumer-error.log',
            out_file: 'logs/product-embedding-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'subscription-consumers',
            script: 'src/SubscriptionConsumers.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/subscription-consumers-error.log',
            out_file: 'logs/subscription-consumers-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'update-admin-consumer',
            script: 'src/UpdateAdminConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/update-admin-consumer-error.log',
            out_file: 'logs/update-admin-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'update-product-consumer',
            script: 'src/UpdateProductConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/update-product-consumer-error.log',
            out_file: 'logs/update-product-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'update-user-cart-consumer',
            script: 'src/UpdateUserCartConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/update-user-cart-consumer-error.log',
            out_file: 'logs/update-user-cart-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
        {
            name: 'update-user-consumer',
            script: 'src/UpdateUserConsumer.ts',
            interpreter: 'tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            disable_logs: false,
            error_file: 'logs/update-user-consumer-error.log',
            out_file: 'logs/update-user-consumer-out.log',
            env: {
                NODE_ENV: 'production',
                PM2_DISABLE_LOGS: 'true',
                PM2_SILENT: 'true'
            },
        },
    ],
};