module.exports = {
    apps: [
        {
            name: 'add-product-consumer',
            script: 'src/AddProductConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'after-order-place-consumer',
            script: 'src/AfterOrderPlaceConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'create-admin-consumer',
            script: 'src/CreateAdminConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'create-user-consumer',
            script: 'src/CreateUserConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'product-embedding-consumer',
            script: 'src/ProductEmbeddingConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'subscription-consumers',
            script: 'src/SubscriptionConsumers.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'update-admin-consumer',
            script: 'src/UpdateAdminConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'update-product-consumer',
            script: 'src/UpdateProductConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'update-user-cart-consumer',
            script: 'src/UpdateUserCartConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'update-user-consumer',
            script: 'src/UpdateUserConsumer.ts',
            interpreter: 'node',
            interpreter_args: '--import tsx',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '300M',
            windowsHide: true,
            env: {
                NODE_ENV: 'production',
            },
        },
    ],
};